# Generated by Django 5.0.1 on 2024-09-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mediaType", models.CharField(max_length=100)),
                ("contentType", models.CharField(max_length=100)),
                ("timePerWeek", models.IntegerField()),
                ("timePerSession", models.IntegerField()),
                ("autodidactOrGuided", models.BooleanField()),
            ],
        ),
    ]
