# Generated by Django 5.0.1 on 2024-09-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preference", "0002_remove_preference_autodidactorguided_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="contentType",
            field=models.CharField(
                choices=[
                    ("Guides", "Guides"),
                    ("Documentation", "Documentation"),
                    ("Introduction", "Introduction"),
                    ("Summary", "Summary"),
                    ("Article", "Article"),
                    ("Quiz", "Quiz"),
                    ("Podcast", "Podcast"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="learningType",
            field=models.CharField(
                choices=[
                    ("Autodidact", "Autodidact"),
                    ("Guided", "Guided"),
                    ("Challenges", "Challenges"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="mediaType",
            field=models.CharField(
                choices=[("Video", "Video"), ("Audio", "Audio"), ("Text", "Text")],
                max_length=100,
            ),
        ),
    ]
