# Generated by Django 5.0.1 on 2024-09-09 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_route", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningrouteresource",
            name="index",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="learningrouteresource",
            name="level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
