# Generated by Django 5.0.1 on 2024-10-08 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preference", "0006_alter_preference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="time_per_session",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(600),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="time_per_week",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(6000),
                ]
            ),
        ),
    ]
