# Generated by Django 5.0.1 on 2024-09-08 00:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_resource', '0003_alter_learningresource_requiredskills'),
        ('skill', '0002_skill_image_skilllevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_resource_index', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('skillLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='LearningRouteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('LearningRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_route.learningroute')),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_resource.learningresource')),
            ],
        ),
        migrations.AddField(
            model_name='learningroute',
            name='learning_resources',
            field=models.ManyToManyField(through='learning_route.LearningRouteResource', to='learning_resource.learningresource'),
        ),
    ]
