# Generated by Django 5.0.1 on 2024-09-08 02:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_resource', '0004_rename_contenttype_learningresource_content_type_and_more'),
        ('skill', '0003_rename_skilltype_skill_skill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRouteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_resource.learningresource')),
            ],
        ),
        migrations.CreateModel(
            name='LearningRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_resource_index', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skilllevel')),
                ('learning_resources', models.ManyToManyField(related_name='learning_route', to='learning_route.learningrouteresource')),
            ],
        ),
    ]
