# Generated by Django 5.0.1 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningroute',
            old_name='skillLevel',
            new_name='skill_level',
        ),
        migrations.RemoveField(
            model_name='learningrouteresource',
            name='LearningRoute',
        ),
        migrations.AlterField(
            model_name='learningroute',
            name='learning_resources',
            field=models.ManyToManyField(related_name='learning_route', to='learning_route.learningrouteresource'),
        ),
    ]
