# Generated by Django 5.0.1 on 2024-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningroute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningrouteresource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
