# Generated by Django 5.0.1 on 2024-09-08 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_route', '0002_alter_learningroute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrouteresource',
            name='time_spent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
