# Generated by Django 5.0.1 on 2024-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_route', '0003_alter_learningrouteresource_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningroute',
            name='learning_resources',
            field=models.ManyToManyField(related_name='learning_route_resources', to='learning_route.learningrouteresource'),
        ),
    ]
