# Generated by Django 5.0.1 on 2024-09-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_skill_image_skilllevel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="skillType",
            new_name="skill_type",
        ),
    ]
