# Generated by Django 5.0.1 on 2024-09-09 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0004_alter_skill_id_alter_skilllevel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MinValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                            ("Text", "Text"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("Guides", "Guides"),
                            ("Documentation", "Documentation"),
                            ("Introduction", "Introduction"),
                            ("Summary", "Summary"),
                            ("Article", "Article"),
                            ("Quiz", "Quiz"),
                            ("Podcast", "Podcast"),
                        ],
                        max_length=100,
                    ),
                ),
                ("link", models.CharField(max_length=200)),
                ("details", models.TextField(blank=True)),
                (
                    "duration",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Spanish"),
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("pt", "Portuguese"),
                            ("zh", "Chinese"),
                            ("hi", "Hindi"),
                            ("ja", "Japanese"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_platform", models.CharField(blank=True, max_length=100)),
                ("original_author", models.CharField(blank=True, max_length=100)),
                (
                    "general_level",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "learning_skills",
                    models.ManyToManyField(
                        related_name="learning_resources_learning",
                        to="skill.skilllevel",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_resources_required",
                        to="skill.skilllevel",
                    ),
                ),
            ],
        ),
    ]
