# Generated by Django 5.0.1 on 2024-09-07 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0002_skill_image_skilllevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mediaType', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Text', 'Text')], max_length=100)),
                ('contentType', models.CharField(choices=[('Guides', 'Guides'), ('Documentation', 'Documentation'), ('Introduction', 'Introduction'), ('Summary', 'Summary'), ('Article', 'Article'), ('Quiz', 'Quiz'), ('Podcast', 'Podcast')], max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('ja', 'Japanese')], max_length=20)),
                ('originalPlatform', models.CharField(max_length=100)),
                ('originalAuthor', models.CharField(max_length=100)),
                ('generalLevel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('learningSkills', models.ManyToManyField(related_name='learning_resources', to='skill.skilllevel')),
                ('requiredSkills', models.ManyToManyField(related_name='required_resources', to='skill.skilllevel')),
            ],
        ),
    ]
