# Generated by Django 5.0.1 on 2024-09-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='originalAuthor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='originalPlatform',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
