# Generated by Django 5.0.1 on 2024-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0002_alter_learningresource_details_and_more'),
        ('skill', '0002_skill_image_skilllevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='requiredSkills',
            field=models.ManyToManyField(blank=True, related_name='required_resources', to='skill.skilllevel'),
        ),
    ]
