# Generated by Django 5.0.1 on 2024-10-08 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resource", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="language",
            field=models.CharField(
                choices=[
                    ("es", "Spanish"),
                    ("en", "English"),
                    ("uk", "Ukrainian"),
                    ("pt", "Portuguese"),
                    ("zh", "Chinese"),
                    ("hi", "Hindi"),
                    ("ja", "Japanese"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
