# Generated by Django 5.0.1 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0003_alter_learningresource_requiredskills'),
        ('skill', '0003_rename_skilltype_skill_skill_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningresource',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='learningresource',
            old_name='generalLevel',
            new_name='general_level',
        ),
        migrations.RenameField(
            model_name='learningresource',
            old_name='mediaType',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='learningresource',
            old_name='originalAuthor',
            new_name='original_author',
        ),
        migrations.RenameField(
            model_name='learningresource',
            old_name='originalPlatform',
            new_name='original_platform',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='learningSkills',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='requiredSkills',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='learning_skills',
            field=models.ManyToManyField(related_name='learning_resources_learning', to='skill.skilllevel'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='learning_resources_required', to='skill.skilllevel'),
        ),
    ]
