# Generated by Django 5.0.1 on 2024-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0004_rename_contenttype_learningresource_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
