# Generated by Django 5.0.1 on 2024-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_route', '0001_initial'),
        ('skill', '0004_alter_skill_id_alter_skilllevel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('current_skills', models.ManyToManyField(blank=True, related_name='users_current', to='skill.skilllevel')),
                ('learning_routes', models.ManyToManyField(blank=True, related_name='users_route', to='learning_route.learningroute')),
                ('target_skills', models.ManyToManyField(blank=True, related_name='users_target', to='skill.skilllevel')),
            ],
        ),
    ]
