# Generated by Django 5.0.1 on 2024-09-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0006_alter_preference_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.preference'),
        ),
    ]
