# Generated by Django 5.0.1 on 2024-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0003_rename_skilltype_skill_skill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skilllevel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
